function TBluetoothManager.GetConnectionState: TBluetoothConnectionState;
begin

end;

function TBluetoothManager.GetCurrentAdapter: TBluetoothAdapter;
begin

end;

class function TBluetoothManager.GetKnownServiceName(const AServiceUUID: TGUID
  ): string;
begin

end;

procedure TBluetoothManager.StartDiscoverable(Timeout: Integer);
begin

end;

procedure TBluetoothManager.StartDiscovery(Timeout: Integer);
begin

end;

procedure TBluetoothManager.CancelDiscovery;
begin

end;

function TBluetoothManager.CreateServerSocket(const AName: string;
  const AUUID: TGUID; Secure: Boolean): TBluetoothServerSocket;
begin

end;

function TBluetoothManager.GetPairedDevices(const AnAdapter: TBluetoothAdapter
  ): TBluetoothDeviceList;
begin

end;

function TBluetoothManager.GetPairedDevices: TBluetoothDeviceList;
begin

end;

